// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables from .env file with fallbacks to previous hardcoded values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hmrkhhibftmubrpejipl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmtoaGliZnRtdWJycGVqaXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjA1NDcsImV4cCI6MjA2MDEzNjU0N30.P-tjM9oTm8Jb3QJ__VoaR79HH8tqTBWcaG83AEaT1EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if environment variables are defined
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase URL and Anon Key must be defined in .env file or use fallback values");
}

// Log which values we're using (helpful for debugging)
console.log(`🔌 Initializing Supabase client with URL: ${SUPABASE_URL.substring(0, 15)}...`);
console.log(`🔑 Using ${import.meta.env.VITE_SUPABASE_ANON_KEY ? 'environment variable' : 'fallback'} for Supabase key`);

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY
);