// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmrkhhibftmubrpejipl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcmtoaGliZnRtdWJycGVqaXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjA1NDcsImV4cCI6MjA2MDEzNjU0N30.P-tjM9oTm8Jb3QJ__VoaR79HH8tqTBWcaG83AEaT1EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);